name: AI Video Generation and Publishing

on:
  schedule:
    - cron: '0 */4 * * *'  # Chạy mỗi 4 giờ (6 lần mỗi ngày)
  workflow_dispatch:     # Cho phép kích hoạt thủ công

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gtts
          
      - name: Set up credentials
        run: |
          mkdir -p credentials
          # Giải mã base64 và lưu file service account
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 -d > credentials/video-al-youtube-c53b44a82d2b.json
          
          # Tạo các file credentials khác
          echo '${{ secrets.YOUTUBE_CLIENT_SECRET }}' > credentials/client_secret.json
          echo '${{ secrets.YOUTUBE_TOKEN }}' > credentials/youtube_token.json
          
          # Tạo file .env
          cat > credentials/.env << EOF
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}
          CREATOMATE_API_KEY=${{ secrets.CREATOMATE_API_KEY }}
          GOOGLE_SHEETS_SPREADSHEET_ID=${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/credentials/video-al-youtube-c53b44a82d2b.json
          YOUTUBE_CLIENT_ID=${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET=${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN=${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          EOF
          
      - name: Verify JSON format
        run: |
          echo "Kiểm tra format file service account..."
          python -c "import json; f=open('credentials/video-al-youtube-c53b44a82d2b.json'); json.load(f); f.close(); print('✅ Service account JSON hợp lệ')"
          
      - name: Create temp directories
        run: |
          mkdir -p temp/images
          mkdir -p temp/videos
          mkdir -p temp/audio
          mkdir -p logs
          
      - name: Run video generation pipeline
        run: python scripts/main.py --all
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials/video-al-youtube-c53b44a82d2b.json

      - name: Upload logs as artifacts 
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: logs/